apiVersion: v1
kind: Pod
spec:
  containers:
    - name: node
      image: node:16
      resources:
        requests:
          memory: '2048Mi'
          cpu: '900m'
        limits:
          memory: '3000Mi'
          cpu: '1200m'
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        allowPrivilegeEscalation: false
      command:
        - cat
      tty: true
    - name: yq
      image: mikefarah/yq:4.4.0
      resources:
        limits:
          memory: '100Mi'
          cpu: '30m'
        requests:
          memory: '50Mi'
          cpu: '10m'
      command:
        - cat
      tty: true
    - name: git
      image: alpine/git:v2.30.0
      resources:
        limits:
          memory: '100Mi'
          cpu: '50m'
        requests:
          memory: '50Mi'
          cpu: '30m'
      command:
        - cat
      tty: true
    - name: docker
      # image: docker:19
      image: ispgweb/docker-aws-cli:1.0
      resources:
        limits:
          memory: '512Mi'
          cpu: '200m'
        requests:
          memory: '256Mi'
          cpu: '100m'
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
